name       : libiconv
version    : '1.16'
release    : 5
source     :
    - https://mirrors.rit.edu/gnu/libiconv/libiconv-1.16.tar.gz : e6a1b1b589654277ee790cce3734f07876ac4ccfaecbee8afa0b649cf529cc04
license    :
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : GNU LIBICONV - character set conversion library
description: This library provides an iconv() implementation, for use on systems which don't have one, or whose implementation cannot convert from/to Unicode.
setup      : |
    %configure
build      : |
    #Ignore a warning in stdio.in.h
    sed -i -e '697d' srclib/stdio.in.h
    %make
install    : |
    %make_install
    # conflicts with glibc iconv
    rm %installroot%/usr/bin/iconv
    rm %installroot%/usr/include/iconv.h
