name       : libiconv
version    : 1.14
release    : 1
source     :
    - http://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.14.tar.gz : 72b24ded17d687193c3366d0ebe7cde1e6b18f0df8c55438ac95be39e8a30613
license    :
    - GPL-3.0
    - LGPL-2.0
summary    : GNU LIBICONV - character set conversion library
description: |
    This library provides an iconv() implementation, for use on systems which don't have one, or whose implementation cannot convert from/to Unicode. 
builddeps  :
setup      : |
    %configure
build      : |
    #Ignore a warning in stdio.in.h
    sed -i -e '697d' srclib/stdio.in.h
    %make
install    : |
    %make_install
